---
title: "Awards"
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



The ICE/ IAMOT Awards :

::: {.infobox .goal data-latex="{.goal}"}
- to the author(s) of the best paper.
- to the person(s) that made the best presentation.
- to the member of the review committee for high quality reviews.
- to the person(s) that conducted the best workshop.
:::


## The “Prof. Bernhard Katzy" Best Paper Award:

The following criteria is used for best paper:

- Scientific contribution
- Relevance in relation to practice
- Argumentation and evidence
- Scope of the paper regarding the conference
- Typography and aesthetics



- Award (2020) – Galvez, Camargo & Schmit. Analysis of SMEs’ Innovation Capability: Towards a Taxonomic Approach based on Internal and Contextual Factors
- Award (2019) – Sasaoka, K.; Takahashi, H.; Minami, Y. (2019) “The Development of a Restroom Car for Women Staffs on Expressway site". Proceedings 25th International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2018) – Tobias Sebastian Schmidt, Bundeswehr University Munich
- Award (2017) – Krawczyk, P.; Topolewski, M.; Pallot, M.: “Towards Reliable and Valid Mixed Methods Instrument in User eXperience Studies”. Proceedings 23nd International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2017) – Bach, J.; Langner, J.; Otten, S.; Holzapfel, M.; Sax, E. – “Test Scenario Selection for System-Level Verification and Validation of Geolocation-Dependent Automotive Control Systems". Proceedings 23nd International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2016) – Wang, B.; Subramanian, A.M.; Chai, K-H.: “Technological Diversity and Firm Performance: The Role of Knowledge Base Homogeneity". Proceedings 22nd International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2015) – Michelino, F.; Lamberti, E.; Cammarano, A.; Caputo, M.: “Dyadic Collaborations and Knowledge Domains: A Patent-based Approach". Proceedings 21st International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2014) – Osorio, J.; Romero, D.; Betancur, M.B.; Molina, A.: “Design for Sustainable Mass-Customization: Design Guidelines for Sustainable Mass-Customized Products". Proceedings 20th International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2013) – Stettina, C.J.; Kroon, E.: “Is there an Agile Handover? An Empirical Study of Documentation and Project Handover Practices Across Agile Software Teams". Proceedings 19th International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2012) – Christidis, K.; Apostolou D.; Mentzas, G.: Our paper “A Socially Intelligent Approach for Enterprise Information Search and Recommendation". Proceedings 18th International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).
- Award (2011) – Song, J.Y., Kracheel, M.; Ziegier, G.; Moser, H.A.: “Critical Interaction Instances in Collaborative Concurrent Engineering". Proceedings 17th International ICE-IEEE ITMC Conference on Engineering, Technology and Innovation (ICE).

This awards is in memory of the recognition for Professor Dr. ***Bernhard R. Katzy (1962-2015) contributions to the ICE Community***^[
Professor Dr. Bernhard R. Katzy was a distinguished scientific engineer as well as project manager, who over his active and diverse career as a professor-at-heart inspired numerous people. He contributed to establishing the field of Technology and Innovation Management on an international level.
<br>
Professor Katzy started his professional career with an apprenticeship as car mechanic and later studied and earned master degrees in electrical engineering and business management. He holds a PhD in industrial management from University of Technology (RWTH) Aachen in Germany and a Habilitation (post-doc PhD) in general management and technology management from University of St. Gallen, Switzerland.
<br>
He was full professor at both, Leiden University and University BW Munich. Here, he founded and built CeTIM Center for Technology and Innovation Management – a spark that ignited various initiatives and projects that will remain. His research interests focused on the growth of high tech businesses and entrepreneurial start-ups, on technology and innovation management, especially in the emerging industrial structures for the information age. Over his career he published more than 140 contributions, amongst over 10 books, about 60 conference and over 30 journal papers.
<br>
Over the last decades Professor Katzy was instrumental in strengthening the ICE International Conference on Engineering, Technology and Innovation Management, and later, from 2004 on, the NITIM Graduate School on Networks, Information Technology and Innovation Management which aims to foster international collaborative, interdisciplinary and intergenerational research among PhD candidates, faculty and industry partners.
<br>
In his early work, he was a pioneer in the field of Virtual Organizations where he worked on organizational patterns for the knowledge society. In that, he aimed at integrating new technologies into Living Lab environments to provide a test bed for network-oriented organization styles and processes, their information and communication technologies.
<br>
Turning with the growth of CeTIM more towards Technology and Innovation Management, he focused on the management of innovation processes, referring to both, production and organizational innovation. Here, he strived for a better organization and understanding of innovation from the viewpoint of the ‘Technopreneur’ by researching organizational routines in entrepreneurship innovation, focusing on the patterns of successful growth, the structuring and restructuring possibilities of a company and its management systems during the innovation phase and the influence of clusters and networks on the innovation process.
<br>
This paved the way for his work in the field of entrepreneurial innovation. For that, he established CeTIM as one of the Entrepreneurship Centers in the Entrepreneurship cluster of Munich, Germany, as well as a shareholder of the international Entrepreneurship Center HTIBI of the City of Beijing, China. With this, he worked on activities of mobilizing and educating entrepreneurs and innovators, and of supporting concrete start-ups and innovation projects. Amongst others, this led to the Global Entrepreneurship Summer School, a yearly challenge with the vision of creating and promoting „Billion Dollar Projects to Foster Societal Change“. The Summer School encourages and connects outstanding students from all over the world to challenge society’s problems by entrepreneurial means.
<br>
Now, more than ever, the principles advocated by Professor Katzy are firmly established in the scientific and practitioners community at the ICE International Conference and will help to shape the vision of young scholars, academics and practitioners in engineering and innovation to create a better world for all of us!
]



## The Best Presentation Award:

- Winning the audience
- Structuring the presentation
- Clearness and understandability
- Quality of AV-aids
- Answering questions

Past winners of this award:

- Award (2019) – Oliveri, M.; Baalsrud Hauge, J.; Bellotti, F.; Berta, R.; De Gloria, A. “Designing an IoT-focused Multiplayer Serious Game for Industry 4.0 Innovation".
- Award(2018) – Kevin Reuther, University of the West of Scotland
- Award (2017) – TBA
- Award (2016) – “A New Perspective on Business Incubator" – Negin Samaeemofrad1, Jaap Van den Herik1, Robert Verburg2, 1Leiden University Leiden, The Netherlands; 2Delft University, The Netherlands.
Award (2015) – “R&D Models for Advanced Development & Corporate Research" – Ikhlaq Sidhu, UC Berkeley University, USA

## The Best Reviewer:

Three main aspects are used as criteria for *best reviewer*:

1. devoted substantial time to review
2. demonstrated precision in comments
3. provided constructive feedback and reliability


- Award (2019) – David Romero, Tecnológico de Monterrey, Mexico
- Award (2018)- Dr. Giovanny Arbelaez-Garces, Université de Lorraine
- Award (2017) – TBA
- Award (2016) – Tor Stålhane, Norwegian University of Science and Technology, Norway
- Award (2016) – Daniele Cerri, Politecnico di Milano, Italy
- Award (2015) – David Romero, Tecnológico de Monterrey, Mexico
- Award (2015) – Judith  Mcknight, University of Ulster, Northern Ireland
- Award (2014) – Thomas Holzmann, Strascheg Center for Entrepreneurship, Germany
- Award (2013) – TBA
- Award (2012) – Ozgur Dedehayir, Leiden University, The Netherlands

## The Best Workshop:

Four aspects are evaluated in the *best workshop*

1. winning the audience
1. structuring the workshop
1. quality of hands-on aids
1. answering questions


- Award(2019) – “A Journey to Intuition in Creativity and Innovation" conducted by Dr. Henri Samier, Arts & Metiers ParisTech, Presence & Innovation Team, LAMPA Lab.
- Award (2017) – TBA
- Award (2016) – Chair: Jaccheri, L. – “LEADERSHIP: 1st International Workshop on the Leadership of Women in Computing Science".
- Award (2015) – Co-Chairs: McAdam, R.; Maki, L. – “Business Process Management in Aerospace".


