---
title: "Registration & Fees"
output:
  distill::distill_article:
    includes:
        in_header: assets/dates.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The registration fees for the conference are outlined below

| **Fees ICE-IAMOT**                                       | Euro  | Dollar\* |
|----------------------------------------------------------|-------|----------|
| Early Bird fees on site (Nancy, France) **until 23 May** | € 450 | \$ 495   |
| Full fees on site **from 24 May**                        | € 600 | \$ 660   |
| Fees On-line                                             | € 250 | \$ 275   |

| **Students Fees ICE-IAMOT**                           | Euro  | Dollar\* |
|-------------------------------------------------------|-------|----------|
| Student fees on site (Nancy, France) **until 23 May** | € 250 | \$ 275   |
| Student Full fees on site **from 24 May**             | € 600 | \$ 660   |
| Student On-line                                       | € 130 | \$ 143   |

| **Extra ticket Gala Dinner [limited number of places]** | € 50 | \$ 55 |
|---------------------------------------------------------|------|-------|

| NITIM PhD Summer School                                                                            |
|----------------------------------------------------------------------------------------------------|
| [NITIM fees or combi-ticket NITIM / ICE-IAMOT](https://ice-iamot-2022-conference.org/1-nitim.html) |

: \* Exchange rates 2022-03-10 for information. Only the rates in Euros are applicable.

This registration fee covers:

-   Submission of papers to IEEE
-   Access to conference proceedings
-   Access to the recorded sessions after the conference
-   Coffee breaks, lunchs and gala dinner
-   Use of conftool submissions systems to manage and process submissions

[**The registration link is open you have to register for ICE-IAMOT 2022 using Conftool.**](https://www.conftool.pro/ice-iamot-2022/index.php?page=participate)

**Please Note:**

-   All authors must pay the whole conference fee, even if they want to join only for the day of their presentation.

-   No reimbursement will be possible after 1st June 2022.
