---
title: "Call for Papers - Workshops"
output:
  distill::distill_article:
    includes:
        in_header: assets/call.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


The $28^{th}$ ICE/ITMC & $31^{st}$ IAMOT Conference IEEE 2022 invites high-quality papers to be presented at this premier international event. Submissions should contribute to a **substantial, original and previously unpublished research in the topics of the conference**.

This includes, but is not limited to:

- Theoretical research papers that provide new concepts in the domain of engineering, technology, and innovation;
- Empirical studies and qualitative case studies that develop new insights;
- System design and development papers that go beyond the pure description of systems and give insight into theory and effectiveness of the approach;
- Verification and validation papers that evaluate the application of solutions.

The review committee is available to provide feedback on abstracts and paper ideas (submit your proposal to ice-iamot-2022-contact@univ-lorraine.fr).

## Workshops and Special issues

If you are interested in submitting a proposal for a workshop or special issue, contact the conference committee at ice-iamot-2022-contact@univ-lorraine.fr and we will provide you with the templates for proposal.

## Key dates

::: {.infobox .goal data-latex="{.goal}"}

- Full paper submission: ~~7 February 2022~~  **7 March 2022**
- Poster submission: **March 2022**
- Full paper and poster notification of acceptance:  **31st March 2022**
- Print-ready IEEE-PDF express-compliant-final papers, copy-right form:  **30th April 2022**

[**Submit your paper on ConfTool Here**](https://www.conftool.pro/ice-iamot-2022)

:::
