---
title: "Templates & Paper Structure"
output:
  distill::distill_article:
    includes:
        in_header: assets/call.html
---


## Templates

Papers will be selected through a double-blind refereeing process based on the submitted full papers.
**Final papers should have no more than 7.000 words (max. 9 pages all inclusive) and must be in the correct format.**
The paper should clearly describe its purpose and relevance, a reference to existing theories and related works, research methods used and major results in engineering, technology and innovation.

::: {.infobox .goal data-latex="{.goal}"}


- [**Word template for the submission here**](assets/paper-template/conference-template-a4-2022.docx)

- [**Submission kit here**](assets/paper-template/2022_ICE_IEEE_Authors Kit.docx)

- [**LaTeX template**](https://www.ieee.org/conferences/publishing/templates.html)


[**Submit your paper on ConfTool Here**](https://www.conftool.pro/ice-iamot-2022)
:::


<!-- Papers are expected to show the following structure: (i) Introduction, (ii) Relation to existing theories and work, (iii) Research/Technology/Innovation approach, (iv) Findings, (v) Conclusion, and (vi) References. -->

Papers are expected to be submitted in A4 format using the ICE/IEEE ICE’2022 paper template that further contains all relevant explanations about papers’ structure and layout as well as needed copyright information.

**Review criteria will be :** 

- (a) The quality of the contribution to the existing body of knowledge in engineering, technology and innovation.
- (b) The relevance of the article in regards to the conference topics. 
- (c) The scientific/innovation quality of the approach described in the de article. 
- (d) The redaction quality and clarity of the article.

Papers will only be accepted for review on the condition that the material is original, that it has not been copyrighted, published, presented or is currently submitted for consideration elsewhere.

Please see our IEEE ICE’2022 Author’s Kit for detailed instructions about all relevant dates, correct submission of needed documents, and Conference Proceedings.

Based on the recommendations of the reviewers, the editorial committee will allocate submissions for oral presentation of papers and/or for poster presentations. Speakers will have 20 minutes for presentation and discussion of their paper. The official language of the conference is English.

The ICE/IEEE ITMC 2022 conference will submit one paper per presenting author only. All accepted, compliant and plagiarism-free papers will be submitted for publication in the digital conference proceedings to be available via IEEE Xplore® (with ISBN Number and DOI for the paper), only if at least one author pays a full registration fee before the deadline.

All Abstracting and Indexing (A&I) providers can be found here: http://ieeeauthorcenter.ieee.org/when-your-article-is-published/abstracting-indexing-ai-databases/ and include amongst others Scopus and Web of Science.

<!-- Authors of selected papers will be invited to submit extensions of the presented work to special issues of indexed scientific journals -->



## Paper Structure

The full paper structure we recommend is the following:

::: {.infobox .goal data-latex="{.goal}"}

**Title**

Abstract<br>
1. Introduction  (Motivation, context, objectives) <br>
2. Existing Theories & Previous Work (Literature Review) <br>
3. Methods <br>
   &nbsp; 3.1 Presented study, Research question & Hypothesis <br>
   &nbsp; 3.2. Applied Research Methods <br>
   &nbsp; 3.3. Research Model(s) & Instrument(s) <br>
   &nbsp; 3.4. Experiment(s) (setup, sample(s), protocol, briefing of participants) <br>
4. Findings <br>
  &nbsp; 4.1 Collected data <br>
  &nbsp; 4.2 Analysis of collected data <br>
  &nbsp; 4.3 Discussion (how much this study answers to the research question and validate <br> hypothesis, validate the model and its related instrument?) <br>
5.  Conclusion <br>
  &nbsp;5.1 Limitations <br>
  &nbsp;5.2 Concluding Remarks (sum-up the main findings and gained new knowledge as well as how <br> this study contributes to the progress in this research field) <br>
  &nbsp; 5.3 Future Work <br>
Acknowledgments <br>
References <br>
:::

**About the Title of your paper:**
Your paper title should be specific, concise, and descriptive. Avoid using unnecessary words such as “new” or “novel;” instead, include some keywords that will help a reader find your paper.

**About your Abstract:**
Your abstract should provide a concise summary of the research conducted, the conclusions reached, and the potential implications of those conclusions.
– Consist of a single paragraph up to 250 words that communicate clearly, with correct grammar and unambiguous terminology;
– Be self-contained, without abbreviations, footnotes, references, or mathematical equations;
– Highlight what is unique in your work;
– Include 3-5 keywords or phrases that describe the research to help readers find your paper.

**About the Introduction section:**
The introduction helps the reader understand why your research is important and what it is contributing to the field. Start by giving the reader a brief overview of the current state of research in your subject area and then progress to more detailed information on the specific topic of your research, ending with a description of the exact question or hypothesis that your paper will address. Also state your motivation for doing your research and what it will contribute to the field.

**About the Methods section:**
– The methods section is where you formulate your research question, including a detailed description of the question, the methods you used to address the question, the definitions of any relevant terminology, and any equations that contributed to your work. 
– The methods section should be described in enough detail for someone to replicate your work.

**About the Findings section:**
This section shows the results you achieved in your work and offers an interpretation of those results. Acknowledge any limitations of your work and avoid exaggerating the importance of the results.

**About the Conclusion section:**
The conclusion summarizes limitations of your study, your key findings, any important conclusions that can be drawn, and further implications for the field. Also discuss benefits or shortcomings of your work and suggest future areas for research.

**About the Acknowledgments section:**
In the acknowledgments section, you can recognize funding source(s), eventually respondents or participants engaged in your experiment(s) and individuals who provided assistance with your work but who do not meet the definition of authorship.The acknowledgments section is optional.

**About the References section:**
This section provides citation information for all the previous publications referred to in your paper. Cite only those references that directly support your work.

